import { StyleSheet } from 'react-native';


export default StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        // width: 400,
    },
    box: {
        // height: 210,
        width: 380,
        backgroundColor: '#FFFFFF',
        marginTop: 10,
        marginLeft: 5,
        marginRight: 5,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#ddd',
        borderBottomWidth: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        marginBottom: 10,
    },
    cardLabel: {
        fontSize:20, 
        marginTop:12,
        marginBottom:8,
        marginLeft:18,
        fontFamily:'ReemKufi'
    },
    divider: {
        borderBottomColor: '#BDBDBD',
        borderBottomWidth: 1,
        marginLeft: 12,
        marginRight: 12
    },
    data: {
          marginTop: 5,
          marginBottom: 5,
          marginLeft: 15,
          marginRight: 15,
        //   flex: 1,
        //   alignItems: 'center'
        //   height: 200,
    },
    button: {
        paddingLeft: 140,
        paddingRight: 140,
        paddingTop: 3,
        paddingBottom: 3,
        borderRadius: 10,
        backgroundColor: '#F0F0F0',
        fontFamily:'ReemKufi'
    },
    cardQuote: {
        fontSize: 25,
        lineHeight: 40,
        alignItems: 'center',
        letterSpacing: .1,
        paddingTop: 25,
        paddingLeft: 30,
        paddingRight: 30,
        paddingBottom: 10,
        width: 380,
        backgroundColor: '#FFFFFF',
        marginTop: 10,
        marginLeft: 5,
        marginRight: 5,
        marginBottom: 10,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#ddd',
        borderBottomWidth: 0,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 5,
        fontFamily: 'ReemKufi'
    },
    category:{
        // flex: 1,
        flexDirection: 'row',
        alignItems: 'stretch',
        // borderWidth: 1,
        marginLeft: 25,
        marginRight: 25,
    },
    categoryDay:{
        alignItems: 'center',
        flex:1,
        // width: 86,
        // alignItems: 'stretch',
        height: 21,
        // marginLeft:17,
        // marginTop: 92,
        backgroundColor:'#F9F9F9',
        borderWidth: 1,
        borderColor: '#6EB1CB',
        borderTopLeftRadius: 10,
        borderBottomLeftRadius: 10,
    },
    categoryWeek:{
        alignItems: 'center',
        // width: 86,
        flex:1,
        height: 21,
        // marginLeft:17,
        // marginTop: 92,
        backgroundColor:'#F9F9F9',
        borderWidth: 1,
        borderColor: '#6EB1CB',
    },
    categoryMonth:{
        alignItems: 'center',
        flex:1,
        // width: 86,
        height: 21,
        // marginLeft:17,
        // marginTop: 92,
        backgroundColor:'#F9F9F9',
        borderWidth: 1,
        borderColor: '#6EB1CB',
    },
    categoryYear:{
        alignItems: 'center',
        flex:1,
        // width: 86,
        height: 21,
        // marginLeft:17,
        // marginTop: 92,
        backgroundColor:'#F9F9F9',
        borderWidth: 1,
        borderColor: '#6EB1CB',
        borderTopRightRadius: 10,
        borderBottomRightRadius: 10,
    },
    listContainer: {
        // flex: 1,
        alignItems: 'stretch',
        // justifyContent: 'space-around',
        // height: 100,
        // flexDirection: 'row',
        // borderWidth: 1,
        padding:2
    },
    listItem: {
        flex: 3,
        alignItems: 'center',
        // flexWrap: 'wrap',
        // height: 100,
        // flexDirection: 'row',
        // borderWidth: 1,
        margin: 3,
        padding: 5,
        // backgroundColor: '#FDBAAF'
        borderRadius: 5
    }
});